<?php 
/*
 * Template Name: Rebelmouse full width
 * Description: template autogenerated by rebelmouse-widget plugin, to use full width.
 * Author: rebelmouse
 * Author URI: http://rebelmouse.com/
 * 
 */
get_header();

while ( have_posts() ) : the_post();
    the_content();
endwhile;

get_footer();
?>
